import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="p-0" >
   
      <Head>
        <title>Avin Mangukiya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-16 px-0 flex-1 flex-col flex justify-center items-center bg-center h-screen max-h-1920 relative">
        <h1 className="m-0 text-6xl text-center">
          HEY, I'M AVIN MANGUKIYA
        </h1>

        <p className="my-16 text-zinc-500 text-2xl text-center w-3/6 ">
          A Frontend focused Web Developer building the Frontend of Websites and Web Applications that leads to the success of the overall product.
        </p>

        <div className="mt-4 text-center">
          <Link href='/project'  >
            <a className="bg-yellow-400 text-black uppercase tracking-wider inline-block font-bold rounded-md transition duration-150 py-16 px-28 text-lg border-none cursor-pointer hover:translate-y-4 shadow-lg shadow-zinc-200 ">
            Projects 
            </a>
          </Link>
        </div>
      </div>
    </div>
  )
}
